# Generated by Django 3.0.5 on 2020-12-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_digest', models.CharField(max_length=100)),
                ('session_token', models.CharField(max_length=100)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
