# Generated by Django 3.0.5 on 2020-12-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='time_added',
            new_name='date_added',
        ),
    ]
