# Generated by Django 3.0.5 on 2020-12-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20201127_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='root_pl_id',
            field=models.PositiveSmallIntegerField(default=25),
            preserve_default=False,
        ),
    ]
