# Generated by Django 3.0.5 on 2020-12-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20201215_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
