# Generated by Django 3.0.5 on 2020-12-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_user_root_pl_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='root_pl_id',
        ),
    ]
