# Generated by Django 3.0.5 on 2021-01-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20210112_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_token',
            new_name='token',
        ),
    ]
