# Generated by Django 3.0.5 on 2020-11-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0002_auto_20201127_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('album', models.CharField(blank=True, max_length=100)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.User')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('songs', models.ManyToManyField(through='song_player.Entry', to='song_player.Song')),
                ('tail_ent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idk', to='song_player.Entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.User')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song_player.Playlist'),
        ),
        migrations.AddField(
            model_name='entry',
            name='prev_ent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_ent', to='song_player.Entry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song_player.Song'),
        ),
    ]
