# Generated by Django 3.0.5 on 2020-11-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='head_entry',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='tail_entry',
        ),
        migrations.RemoveField(
            model_name='playlist_entry',
            name='next_entry',
        ),
        migrations.AddField(
            model_name='playlist',
            name='head_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tail_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist_entry',
            name='next_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
