# Generated by Django 3.0.5 on 2020-11-29 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='prev_ent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_ent', to='song_player.Entry'),
        ),
    ]
