# Generated by Django 3.0.5 on 2020-12-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(through='song_player.Entry', to='song_player.Playlist'),
        ),
    ]
