# Generated by Django 3.0.5 on 2020-12-12 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_remove_user_root_pl_id'),
        ('song_player', '0002_song_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='root_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_pl', to='user_auth.User'),
        ),
    ]
