# Generated by Django 3.0.5 on 2020-12-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_player', '0003_song_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='yt_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
