# Generated by Django 3.0.5 on 2020-11-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_player', '0003_auto_20201109_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='next_id',
            new_name='prev_id',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='head_id',
        ),
    ]
