# Generated by Django 3.0.5 on 2020-12-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_player', '0003_auto_20201129_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
