# Generated by Django 3.0.5 on 2020-12-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_player', '0003_playlist_root_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='root_user',
        ),
    ]
