# Generated by Django 3.0.5 on 2020-11-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_player', '0004_auto_20201109_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='waveform',
        ),
        migrations.AddField(
            model_name='song',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
