# Generated by Django 3.0.5 on 2020-11-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_player', '0005_auto_20201116_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
