# Generated by Django 3.0.5 on 2020-11-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_player', '0006_auto_20201116_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='prev_ent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='song_player.Entry'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tail_ent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idk', to='song_player.Entry'),
        ),
    ]
