# Generated by Django 3.0.5 on 2020-11-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_player', '0009_auto_20201126_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tail_ent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idk', to='song_player.Entry'),
        ),
    ]
