# Generated by Django 3.0.5 on 2020-11-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_player', '0011_auto_20201126_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='prev_id',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='tail_id',
        ),
    ]
