"""
Django settings for music_player_1 project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import psycopg2
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
  'DJANGO_SECRET_KEY', 'z7t+y3%z6n&-$==3*@q#9@6b)!c+!3h1ftoqz_8su6n70mm*k%')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'PROD' not in os.environ


ALLOWED_HOSTS = [
  'music-player-1.herokuapp.com', '127.0.0.1', '0.0.0.0', 'localhost'
]
# Application definition

INSTALLED_APPS = [
  'whitenoise.runserver_nostatic',
  'user_auth.apps.UserAuthConfig',
  'song_player.apps.SongPlayerConfig',
  # 'django.contrib.admin',
  # 'django.contrib.auth',
  # 'django.contrib.contenttypes',
  # 'django.contrib.sessions', # db based caching
  # 'django.contrib.messages',
  'django.contrib.staticfiles', # needed for collect static
  # 'debug_toolbar',
]

MIDDLEWARE = [
  # 'django.middleware.security.SecurityMiddleware',
  'whitenoise.middleware.WhiteNoiseMiddleware', # host static files
  'django.contrib.sessions.middleware.SessionMiddleware', #for cookies
  # 'django.middleware.common.CommonMiddleware',
  # 'django.middleware.csrf.CsrfViewMiddleware',
  # 'debug_toolbar.middleware.DebugToolbarMiddleware',
  # 'django.contrib.auth.middleware.AuthenticationMiddleware',
  # 'django.contrib.messages.middleware.MessageMiddleware',
  # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'music_player_1.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [os.path.join(BASE_DIR, 'templates')],
    'APP_DIRS': True, # seemingly only needed for debug toolbar
    # 'OPTIONS': {
    #   'context_processors': [
    #     'django.template.context_processors.debug',
    #     'django.template.context_processors.request',
    #     'django.contrib.auth.context_processors.auth',
    #     'django.contrib.messages.context_processors.messages',
    #   ],
    # },
  },
]

WSGI_APPLICATION = 'music_player_1.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
  'default':
    dj_database_url.parse(
      'postgres://turdkgefwhlmsz:01318749e71c700d2145eca8df45370884b930983076553f2f6d8bfa0b67b2f4@ec2-54-158-190-214.compute-1.amazonaws.com:5432/dbuqo2f237hbof',
      conn_max_age=600,
      ssl_require=True)
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
# AUTH_PASSWORD_VALIDATORS = [
#   {
#     'NAME':
#       'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#   },
#   {
#     'NAME':
#       'django.contrib.auth.password_validation.MinimumLengthValidator',
#   },
#   {
#     'NAME':
#       'django.contrib.auth.password_validation.CommonPasswordValidator',
#   },
#   {
#     'NAME':
#       'django.contrib.auth.password_validation.NumericPasswordValidator',
#   },
# ]

# Internationalization
# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/' # relative url
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # destination of collectstatic, whitenoise target during prod
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] #source(s) of collectstatic, whitenoise target during debug
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"


AWS_ACCESS_KEY_ID = os.environ.get('MP1_AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('MP1_AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('MP1_AWS_STORAGE_BUCKET_NAME', '')


INTERNAL_IPS = [
    '127.0.0.1',
] # for debug toolbar
